name: ecommerceapp
description: "A new Flutter e-commerce application."
# Restrict accidental publishing:
publish_to: 'none'

# Version and build details:
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  get: ^4.6.6
  intl: ^0.19.0
  http: ^1.2.2
  cached_network_image: ^3.3.1
  # Removed duplicate entry
  image_picker: ^1.1.2  # Keep the correct version
  show_up_animation: ^2.0.0
  auto_animated: ^3.2.0
  flutter_polyline_points: ^2.1.0
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  firebase_messaging: ^15.0.3
  firebase_core: ^3.2.0
  flutter_local_notifications: ^17.2.1+2
  cloud_firestore: ^5.1.0
  sqflite: ^2.3.3+1
  shared_preferences: ^2.2.3
  path: ^1.9.0
  qr_flutter: ^4.1.0
  scan: ^1.6.0
  grouped_list: ^6.0.0
  url_launcher: ^6.2.0
  dropdown_search: ^5.0.6
  badges: ^3.1.2
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.2.1
  flutter_launcher_icons: ^0.13.1
  dartz: ^0.10.1  # No update available yet
  google_sign_in: ^6.2.1
  device_preview: ^1.2.0
  responsive_builder: ^0.7.1
  animate_do: ^2.0.0
  flutter_otp_text_field: ^1.1.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Updated to latest version for code analysis

flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/fonts/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700

    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Bold.ttf
          weight: 700

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

